format = """
[░▒▓](#A9B1D6)\
[  ](bg:#A9B1D6 fg:#212736)\
[](bg:#7AA2F7 fg:#A9B1D6)\
$sudo\
$directory\
[](fg:#7AA2F7 bg:#394260)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
[](fg:#394260 bg:#212736)\
$c\
$cmake\
$golang\
$haskell\
$java\
$kotlin\
$gradle\
$lua\
$perl\
$python\
$rust\
$zig\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
$fill\
$battery\
$memory_usage\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$shell\
$character"""

[battery]
format = '[$symbol]($style)'

[[battery.display]]
threshold = 20
style = 'bold red'
charging_symbol = ' '
discharging_symbol = '  '

[[battery.display]]
threshold = 50
style = 'bold yellow'
charging_symbol = ' '
discharging_symbol = '  '

[c]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[dart]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[directory]
style = "fg:#e3e5e5 bg:#7AA2F7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#7AA2F7 bg:#394260)]($style)'

[git_branch]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#7AA2F7 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#7AA2F7 bg:#394260)]($style)'

[fill]
symbol = " "

[golang]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[haskell]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[java]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol](fg:#7AA2F7 bg:#212736)]($style)'

[lua]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

# [nodejs]
# symbol = " "

[ocaml]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[python]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[rust]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7AA2F7 bg:#212736)]($style)'

[sudo]
disabled = false
style = "fg:#e3e5e5 bg:#7AA2F7"
format = '[ $symbol]($style)'
symbol = ' '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[username]
style_root = 'bold red'
style_user = 'bold yellow'
format = "[$user]($style) "
show_always = false
